version: "3.9"

services:
  page-indexer:
    build: ./page-indexer
    env_file:
      - .env
    ports:
      - "8080:8080"

  hf-embedder:
    build: ./hf-embedder
    ports:
      - "8000:8000"

  page-content-processor:
    build: ./page-content-processor
    env_file:
      - .env
    environment:
      HF_EMBEDDER_URL: http://hf-embedder:8000/
    ports:
      - "8001:8000"

  page-indexer-trigger:
    build: ./page-indexer-trigger
    env_file:
      - .env
    environment:
      PAGE_INDEXER_URL: http://page-indexer:8080/
    profiles:
      - trigger
