version: "3.9"

services:
  page-indexer:
    build:
      context: .
      dockerfile: services/page_indexer/Dockerfile
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "8000:8000"

  page-indexer-trigger:
    build:
      context: .
      dockerfile: jobs/page_indexer_trigger/Dockerfile
    env_file:
      - .env
    environment:
      PAGE_INDEXER_URL: http://page-indexer:8000/
    profiles:
      - trigger
    restart: "no"

  page-processor-oneoff:
    build:
      context: .
      dockerfile: jobs/page_processor/jobs/one_off/Dockerfile
    env_file:
      - .env
    profiles:
      - trigger
    restart: "no"

  promtail:
    image: grafana/promtail:2.9.4
    container_name: promtail
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: -config.file=/etc/promtail/config.yml
    restart: unless-stopped
