apiVersion: batch/v1
kind: Job
metadata:
  name: page-processor-trigger
  namespace: nucleus-ai
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      labels:
        app: page-processor-trigger
    spec:
      restartPolicy: Never
      containers:
        - name: page-processor-trigger
          image: nucleus-ai-page-processor-trigger:latest
          env:
            - name: PAGE_PROCESSOR_URL
              value: http://page-processor:8000
          envFrom:
            - configMapRef:
                name: nucleus-ai-env
          imagePullPolicy: IfNotPresent
